OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: 
  if_use: false # 如果不用OpenAI的就用ChatGLM的

GLMModel:
  model: "glm-4"
  api_key: 

common:
  book: "openai-translator/tests/test.pdf"
  file_format: "markdown"